package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Actividadempresa generated by hbm2java
 */
public class Actividadempresa  implements java.io.Serializable {


     private ActividadempresaId id;
     private String prioridad;

    public Actividadempresa() {
    }

    public Actividadempresa(ActividadempresaId id, String prioridad) {
       this.id = id;
       this.prioridad = prioridad;
    }
   
    public ActividadempresaId getId() {
        return this.id;
    }
    
    public void setId(ActividadempresaId id) {
        this.id = id;
    }
    public String getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }




}


