package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int cuacm;
     private String nombreActividad;
     private int estandar;
     private char grupo;

    public Actividad() {
    }

    public Actividad(int cuacm, String nombreActividad, int estandar, char grupo) {
       this.cuacm = cuacm;
       this.nombreActividad = nombreActividad;
       this.estandar = estandar;
       this.grupo = grupo;
    }
   
    public int getCuacm() {
        return this.cuacm;
    }
    
    public void setCuacm(int cuacm) {
        this.cuacm = cuacm;
    }
    public String getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public int getEstandar() {
        return this.estandar;
    }
    
    public void setEstandar(int estandar) {
        this.estandar = estandar;
    }
    public char getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(char grupo) {
        this.grupo = grupo;
    }




}


