package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private DomicilioId id;
     private long cuit;
     private Integer piso;
     private String depto;
     private int localidad;
     private int telefono;
     private String email;
     private String zonificacion;
     private Integer idPlanta;
     private String nroPartida;

    public Domicilio() {
    }

	
    public Domicilio(DomicilioId id, long cuit, int localidad, int telefono, String email, String zonificacion) {
        this.id = id;
        this.cuit = cuit;
        this.localidad = localidad;
        this.telefono = telefono;
        this.email = email;
        this.zonificacion = zonificacion;
    }
    public Domicilio(DomicilioId id, long cuit, Integer piso, String depto, int localidad, int telefono, String email, String zonificacion, Integer idPlanta, String nroPartida) {
       this.id = id;
       this.cuit = cuit;
       this.piso = piso;
       this.depto = depto;
       this.localidad = localidad;
       this.telefono = telefono;
       this.email = email;
       this.zonificacion = zonificacion;
       this.idPlanta = idPlanta;
       this.nroPartida = nroPartida;
    }
   
    public DomicilioId getId() {
        return this.id;
    }
    
    public void setId(DomicilioId id) {
        this.id = id;
    }
    public long getCuit() {
        return this.cuit;
    }
    
    public void setCuit(long cuit) {
        this.cuit = cuit;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }
    public int getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(int localidad) {
        this.localidad = localidad;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getZonificacion() {
        return this.zonificacion;
    }
    
    public void setZonificacion(String zonificacion) {
        this.zonificacion = zonificacion;
    }
    public Integer getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(Integer idPlanta) {
        this.idPlanta = idPlanta;
    }
    public String getNroPartida() {
        return this.nroPartida;
    }
    
    public void setNroPartida(String nroPartida) {
        this.nroPartida = nroPartida;
    }




}


