package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * DomicilioId generated by hbm2java
 */
public class DomicilioId  implements java.io.Serializable {


     private String tipo;
     private String calle;
     private String numero;

    public DomicilioId() {
    }

    public DomicilioId(String tipo, String calle, String numero) {
       this.tipo = tipo;
       this.calle = calle;
       this.numero = numero;
    }
   
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DomicilioId) ) return false;
		 DomicilioId castOther = ( DomicilioId ) other; 
         
		 return ( (this.getTipo()==castOther.getTipo()) || ( this.getTipo()!=null && castOther.getTipo()!=null && this.getTipo().equals(castOther.getTipo()) ) )
 && ( (this.getCalle()==castOther.getCalle()) || ( this.getCalle()!=null && castOther.getCalle()!=null && this.getCalle().equals(castOther.getCalle()) ) )
 && ( (this.getNumero()==castOther.getNumero()) || ( this.getNumero()!=null && castOther.getNumero()!=null && this.getNumero().equals(castOther.getNumero()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipo() == null ? 0 : this.getTipo().hashCode() );
         result = 37 * result + ( getCalle() == null ? 0 : this.getCalle().hashCode() );
         result = 37 * result + ( getNumero() == null ? 0 : this.getNumero().hashCode() );
         return result;
   }   


}


