package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Efluente generated by hbm2java
 */
public class Efluente  implements java.io.Serializable {


     private Integer idEfluente;
     private String procesoGenerador;
     private String componentesRelevantes;
     private double volumen;
     private String unidad;
     private String unidadDeTiempo;
     private String gestion;
     private String cuerpoReceptor;
     private int idPlanta;
     private String tipo;

    public Efluente() {
    }

    public Efluente(String procesoGenerador, String componentesRelevantes, double volumen, String unidad, String unidadDeTiempo, String gestion, String cuerpoReceptor, int idPlanta, String tipo) {
       this.procesoGenerador = procesoGenerador;
       this.componentesRelevantes = componentesRelevantes;
       this.volumen = volumen;
       this.unidad = unidad;
       this.unidadDeTiempo = unidadDeTiempo;
       this.gestion = gestion;
       this.cuerpoReceptor = cuerpoReceptor;
       this.idPlanta = idPlanta;
       this.tipo = tipo;
    }
   
    public Integer getIdEfluente() {
        return this.idEfluente;
    }
    
    public void setIdEfluente(Integer idEfluente) {
        this.idEfluente = idEfluente;
    }
    public String getProcesoGenerador() {
        return this.procesoGenerador;
    }
    
    public void setProcesoGenerador(String procesoGenerador) {
        this.procesoGenerador = procesoGenerador;
    }
    public String getComponentesRelevantes() {
        return this.componentesRelevantes;
    }
    
    public void setComponentesRelevantes(String componentesRelevantes) {
        this.componentesRelevantes = componentesRelevantes;
    }
    public double getVolumen() {
        return this.volumen;
    }
    
    public void setVolumen(double volumen) {
        this.volumen = volumen;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public String getUnidadDeTiempo() {
        return this.unidadDeTiempo;
    }
    
    public void setUnidadDeTiempo(String unidadDeTiempo) {
        this.unidadDeTiempo = unidadDeTiempo;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public String getCuerpoReceptor() {
        return this.cuerpoReceptor;
    }
    
    public void setCuerpoReceptor(String cuerpoReceptor) {
        this.cuerpoReceptor = cuerpoReceptor;
    }
    public int getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(int idPlanta) {
        this.idPlanta = idPlanta;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


