package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Emisiongaseosa generated by hbm2java
 */
public class Emisiongaseosa  implements java.io.Serializable {


     private Integer idEmisionGaseosa;
     private String tipo;
     private String emision;
     private String procesoGenerador;
     private String tratamiento;
     private String componentesRelevantes;
     private int idPlanta;

    public Emisiongaseosa() {
    }

    public Emisiongaseosa(String tipo, String emision, String procesoGenerador, String tratamiento, String componentesRelevantes, int idPlanta) {
       this.tipo = tipo;
       this.emision = emision;
       this.procesoGenerador = procesoGenerador;
       this.tratamiento = tratamiento;
       this.componentesRelevantes = componentesRelevantes;
       this.idPlanta = idPlanta;
    }
   
    public Integer getIdEmisionGaseosa() {
        return this.idEmisionGaseosa;
    }
    
    public void setIdEmisionGaseosa(Integer idEmisionGaseosa) {
        this.idEmisionGaseosa = idEmisionGaseosa;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEmision() {
        return this.emision;
    }
    
    public void setEmision(String emision) {
        this.emision = emision;
    }
    public String getProcesoGenerador() {
        return this.procesoGenerador;
    }
    
    public void setProcesoGenerador(String procesoGenerador) {
        this.procesoGenerador = procesoGenerador;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public String getComponentesRelevantes() {
        return this.componentesRelevantes;
    }
    
    public void setComponentesRelevantes(String componentesRelevantes) {
        this.componentesRelevantes = componentesRelevantes;
    }
    public int getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(int idPlanta) {
        this.idPlanta = idPlanta;
    }




}


