package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private long cuit;
     private String razonSocial;
     private Date fechaInicioActividades;
     private String tipoPersona;
     private Integer nroRegistro;

    public Empresa() {
    }

	
    public Empresa(long cuit, String razonSocial, Date fechaInicioActividades, String tipoPersona) {
        this.cuit = cuit;
        this.razonSocial = razonSocial;
        this.fechaInicioActividades = fechaInicioActividades;
        this.tipoPersona = tipoPersona;
    }
    public Empresa(long cuit, String razonSocial, Date fechaInicioActividades, String tipoPersona, Integer nroRegistro) {
       this.cuit = cuit;
       this.razonSocial = razonSocial;
       this.fechaInicioActividades = fechaInicioActividades;
       this.tipoPersona = tipoPersona;
       this.nroRegistro = nroRegistro;
    }
   
    public long getCuit() {
        return this.cuit;
    }
    
    public void setCuit(long cuit) {
        this.cuit = cuit;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Date getFechaInicioActividades() {
        return this.fechaInicioActividades;
    }
    
    public void setFechaInicioActividades(Date fechaInicioActividades) {
        this.fechaInicioActividades = fechaInicioActividades;
    }
    public String getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public Integer getNroRegistro() {
        return this.nroRegistro;
    }
    
    public void setNroRegistro(Integer nroRegistro) {
        this.nroRegistro = nroRegistro;
    }




}


