package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Formaciondepersonal generated by hbm2java
 */
public class Formaciondepersonal  implements java.io.Serializable {


     private Integer idFormacionPersonal;
     private int cantidadObreros;
     private boolean capacitacionObreros;
     private int cantidadTecnicos;
     private boolean capacitacionTecnicos;
     private int cantidadProfesionales;
     private boolean capacitacionProfesionales;
     private int idPlanta;

    public Formaciondepersonal() {
    }

    public Formaciondepersonal(int cantidadObreros, boolean capacitacionObreros, int cantidadTecnicos, boolean capacitacionTecnicos, int cantidadProfesionales, boolean capacitacionProfesionales, int idPlanta) {
       this.cantidadObreros = cantidadObreros;
       this.capacitacionObreros = capacitacionObreros;
       this.cantidadTecnicos = cantidadTecnicos;
       this.capacitacionTecnicos = capacitacionTecnicos;
       this.cantidadProfesionales = cantidadProfesionales;
       this.capacitacionProfesionales = capacitacionProfesionales;
       this.idPlanta = idPlanta;
    }
   
    public Integer getIdFormacionPersonal() {
        return this.idFormacionPersonal;
    }
    
    public void setIdFormacionPersonal(Integer idFormacionPersonal) {
        this.idFormacionPersonal = idFormacionPersonal;
    }
    public int getCantidadObreros() {
        return this.cantidadObreros;
    }
    
    public void setCantidadObreros(int cantidadObreros) {
        this.cantidadObreros = cantidadObreros;
    }
    public boolean isCapacitacionObreros() {
        return this.capacitacionObreros;
    }
    
    public void setCapacitacionObreros(boolean capacitacionObreros) {
        this.capacitacionObreros = capacitacionObreros;
    }
    public int getCantidadTecnicos() {
        return this.cantidadTecnicos;
    }
    
    public void setCantidadTecnicos(int cantidadTecnicos) {
        this.cantidadTecnicos = cantidadTecnicos;
    }
    public boolean isCapacitacionTecnicos() {
        return this.capacitacionTecnicos;
    }
    
    public void setCapacitacionTecnicos(boolean capacitacionTecnicos) {
        this.capacitacionTecnicos = capacitacionTecnicos;
    }
    public int getCantidadProfesionales() {
        return this.cantidadProfesionales;
    }
    
    public void setCantidadProfesionales(int cantidadProfesionales) {
        this.cantidadProfesionales = cantidadProfesionales;
    }
    public boolean isCapacitacionProfesionales() {
        return this.capacitacionProfesionales;
    }
    
    public void setCapacitacionProfesionales(boolean capacitacionProfesionales) {
        this.capacitacionProfesionales = capacitacionProfesionales;
    }
    public int getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(int idPlanta) {
        this.idPlanta = idPlanta;
    }




}


