package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int id;
     private String nombreLocalidad;
     private int idDepartamento;
     private int idNodo;
     private String categoria;
     private String codigoPostal;

    public Localidad() {
    }

    public Localidad(int id, String nombreLocalidad, int idDepartamento, int idNodo, String categoria, String codigoPostal) {
       this.id = id;
       this.nombreLocalidad = nombreLocalidad;
       this.idDepartamento = idDepartamento;
       this.idNodo = idNodo;
       this.categoria = categoria;
       this.codigoPostal = codigoPostal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreLocalidad() {
        return this.nombreLocalidad;
    }
    
    public void setNombreLocalidad(String nombreLocalidad) {
        this.nombreLocalidad = nombreLocalidad;
    }
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public int getIdNodo() {
        return this.idNodo;
    }
    
    public void setIdNodo(int idNodo) {
        this.idNodo = idNodo;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }




}


