package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Nodo generated by hbm2java
 */
public class Nodo  implements java.io.Serializable {


     private int idNodo;
     private String nombreNodo;

    public Nodo() {
    }

    public Nodo(int idNodo, String nombreNodo) {
       this.idNodo = idNodo;
       this.nombreNodo = nombreNodo;
    }
   
    public int getIdNodo() {
        return this.idNodo;
    }
    
    public void setIdNodo(int idNodo) {
        this.idNodo = idNodo;
    }
    public String getNombreNodo() {
        return this.nombreNodo;
    }
    
    public void setNombreNodo(String nombreNodo) {
        this.nombreNodo = nombreNodo;
    }




}


