package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Planta generated by hbm2java
 */
public class Planta  implements java.io.Serializable {


     private Integer idPlanta;
     private long cuit;
     private boolean fueraProv;
     private Double superficieDeposito;
     private double superficieTotalM2;
     private double superficieCubiertaM2;
     private double potenciaInstaladaHp;
     private int dotacionDePersonal;
     private Date fechaInicioActividades;

    public Planta() {
    }

	
    public Planta(long cuit, boolean fueraProv, double superficieTotalM2, double superficieCubiertaM2, double potenciaInstaladaHp, int dotacionDePersonal, Date fechaInicioActividades) {
        this.cuit = cuit;
        this.fueraProv = fueraProv;
        this.superficieTotalM2 = superficieTotalM2;
        this.superficieCubiertaM2 = superficieCubiertaM2;
        this.potenciaInstaladaHp = potenciaInstaladaHp;
        this.dotacionDePersonal = dotacionDePersonal;
        this.fechaInicioActividades = fechaInicioActividades;
    }
    public Planta(long cuit, boolean fueraProv, Double superficieDeposito, double superficieTotalM2, double superficieCubiertaM2, double potenciaInstaladaHp, int dotacionDePersonal, Date fechaInicioActividades) {
       this.cuit = cuit;
       this.fueraProv = fueraProv;
       this.superficieDeposito = superficieDeposito;
       this.superficieTotalM2 = superficieTotalM2;
       this.superficieCubiertaM2 = superficieCubiertaM2;
       this.potenciaInstaladaHp = potenciaInstaladaHp;
       this.dotacionDePersonal = dotacionDePersonal;
       this.fechaInicioActividades = fechaInicioActividades;
    }
   
    public Integer getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(Integer idPlanta) {
        this.idPlanta = idPlanta;
    }
    public long getCuit() {
        return this.cuit;
    }
    
    public void setCuit(long cuit) {
        this.cuit = cuit;
    }
    public boolean isFueraProv() {
        return this.fueraProv;
    }
    
    public void setFueraProv(boolean fueraProv) {
        this.fueraProv = fueraProv;
    }
    public Double getSuperficieDeposito() {
        return this.superficieDeposito;
    }
    
    public void setSuperficieDeposito(Double superficieDeposito) {
        this.superficieDeposito = superficieDeposito;
    }
    public double getSuperficieTotalM2() {
        return this.superficieTotalM2;
    }
    
    public void setSuperficieTotalM2(double superficieTotalM2) {
        this.superficieTotalM2 = superficieTotalM2;
    }
    public double getSuperficieCubiertaM2() {
        return this.superficieCubiertaM2;
    }
    
    public void setSuperficieCubiertaM2(double superficieCubiertaM2) {
        this.superficieCubiertaM2 = superficieCubiertaM2;
    }
    public double getPotenciaInstaladaHp() {
        return this.potenciaInstaladaHp;
    }
    
    public void setPotenciaInstaladaHp(double potenciaInstaladaHp) {
        this.potenciaInstaladaHp = potenciaInstaladaHp;
    }
    public int getDotacionDePersonal() {
        return this.dotacionDePersonal;
    }
    
    public void setDotacionDePersonal(int dotacionDePersonal) {
        this.dotacionDePersonal = dotacionDePersonal;
    }
    public Date getFechaInicioActividades() {
        return this.fechaInicioActividades;
    }
    
    public void setFechaInicioActividades(Date fechaInicioActividades) {
        this.fechaInicioActividades = fechaInicioActividades;
    }




}


