package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Representante generated by hbm2java
 */
public class Representante  implements java.io.Serializable {


     private int documento;
     private String apellido;
     private String nombre;
     private String cargo;
     private long cuit;
     private String tipo;

    public Representante() {
    }

    public Representante(int documento, String apellido, String nombre, String cargo, long cuit, String tipo) {
       this.documento = documento;
       this.apellido = apellido;
       this.nombre = nombre;
       this.cargo = cargo;
       this.cuit = cuit;
       this.tipo = tipo;
    }
   
    public int getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(int documento) {
        this.documento = documento;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public long getCuit() {
        return this.cuit;
    }
    
    public void setCuit(long cuit) {
        this.cuit = cuit;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


