package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Residuosolido generated by hbm2java
 */
public class Residuosolido  implements java.io.Serializable {


     private Integer idResiduoSolido;
     private String residuo;
     private double cantidad;
     private String unidad;
     private String periodo;
     private String procesoGenerador;
     private String gestion;
     private int idPlanta;
     private String tipo;

    public Residuosolido() {
    }

    public Residuosolido(String residuo, double cantidad, String unidad, String periodo, String procesoGenerador, String gestion, int idPlanta, String tipo) {
       this.residuo = residuo;
       this.cantidad = cantidad;
       this.unidad = unidad;
       this.periodo = periodo;
       this.procesoGenerador = procesoGenerador;
       this.gestion = gestion;
       this.idPlanta = idPlanta;
       this.tipo = tipo;
    }
   
    public Integer getIdResiduoSolido() {
        return this.idResiduoSolido;
    }
    
    public void setIdResiduoSolido(Integer idResiduoSolido) {
        this.idResiduoSolido = idResiduoSolido;
    }
    public String getResiduo() {
        return this.residuo;
    }
    
    public void setResiduo(String residuo) {
        this.residuo = residuo;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getProcesoGenerador() {
        return this.procesoGenerador;
    }
    
    public void setProcesoGenerador(String procesoGenerador) {
        this.procesoGenerador = procesoGenerador;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public int getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(int idPlanta) {
        this.idPlanta = idPlanta;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


