package Modelo;
// Generated 25-sep-2019 10:57:58 by Hibernate Tools 4.3.1



/**
 * Tanque generated by hbm2java
 */
public class Tanque  implements java.io.Serializable {


     private Integer idTanque;
     private int cantidad;
     private double capacidadTotal;
     private String unidad;
     private int idPlanta;

    public Tanque() {
    }

    public Tanque(int cantidad, double capacidadTotal, String unidad, int idPlanta) {
       this.cantidad = cantidad;
       this.capacidadTotal = capacidadTotal;
       this.unidad = unidad;
       this.idPlanta = idPlanta;
    }
   
    public Integer getIdTanque() {
        return this.idTanque;
    }
    
    public void setIdTanque(Integer idTanque) {
        this.idTanque = idTanque;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getCapacidadTotal() {
        return this.capacidadTotal;
    }
    
    public void setCapacidadTotal(double capacidadTotal) {
        this.capacidadTotal = capacidadTotal;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public int getIdPlanta() {
        return this.idPlanta;
    }
    
    public void setIdPlanta(int idPlanta) {
        this.idPlanta = idPlanta;
    }




}


